### ISSUE TITLE
Random Error - Missing Geometry Issue

### ISSUE THREAD

**Issue by Ameno-Sagiri** [theturboturnip/yk_gmd_io#13]
Using `yk_gmd_blender_v0_2_1`
I just stumbled across this tool. It seems to work well for a few smaller models I've tried, but I understand it must not be ready to handle much more complex models yet, since every one I've tried usually gets met with an error. I'm also assuming you're probably already aware of this error.

As a background, I examined the model `st_k_ramen.gmd from Yakuza 0 `in Noesis after converting to ASCII using Yakuza 6 tools, then FBX then opening into Blender. It's quite literally the entire interior to a Ramen shop. All materials except for universal materials like `"dummy_white"` are located in the folder alongside the gmd as dds format, if that matters.

I tried to directly import said gmd file using your importer, and was met with this error.
![blender_2020-12-03_16-09-36](https://user-images.githubusercontent.com/5976053/101094689-6a472480-3582-11eb-89a3-dcab822504b8.png)

Here's the result. It's missing roughly 70% of the model.
![blender_2020-12-03_16-13-54](https://user-images.githubusercontent.com/5976053/101094788-919df180-3582-11eb-8ea2-db0e60e9dc45.png)

For reference, here's my output FBX from Noesis of the same model (I hid the ceiling geometry)
![blender_2020-12-03_16-17-05](https://user-images.githubusercontent.com/5976053/101095107-096c1c00-3583-11eb-8dec-87de03e24e72.png)

Very nice tool, I really hope you continue to work on it.

**Comment by reddohme** [comment]
Same issue. It only happens when the "fuse vertice" option is enabled. You can disable that and it'll import all pieces but it was hit or miss whether or not it'd import materials with it. This was done with y0 Maharaja, haven't tested with any stages from the other games.
<img width="1920" alt="blender_xl0bYZSIRH" src="https://user-images.githubusercontent.com/37015524/106529422-47ac8b80-649f-11eb-97c3-5c54ec478b36.png">

**Comment by theturboturnip** [comment]
![image](https://user-images.githubusercontent.com/5640008/124391933-eb1df880-dcea-11eb-97ba-cc1cb1d90f80.png)
![image](https://user-images.githubusercontent.com/5640008/124391963-143e8900-dceb-11eb-9ef1-d0682617d785.png)

These should be fixed with the upcoming v0.3.0 update - these screenshots were taken from imports using the new "Unskinned" option.

**Comment by theturboturnip** [comment]
(Upcoming as in releasing later today probably)
